export { default as Login } from './Authen/Index'
export {default as Dashboard} from './Dashboard/Index'
export { default as ECM } from './ECM/Index'
export { default as LOS } from './LOS/Index'
export { default as BOS } from './BOS/Index'
export { default as BMS } from './BMS/Index'
export { default as TMS } from './TMS/Index'
export { default as NotFound } from './NotFound/Index'
